AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  DisplayStyleGuide: true
  Exclude:
    - test/dummy/db/**/*.rb
    - vendor/**/*
    - gemfiles/vendor/**/*

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ConstantVisibility:
  Enabled: true

Style/DateTime:
  Enabled: true

Style/Documentation:
  Exclude:
    - test/**/*.rb
    - db/migrate/*.rb

Style/ImplicitRuntimeError:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  AllowParenthesesInCamelCaseMethod: true
  IgnoredMethods:
    - add_dependency
    - add_development_dependency
    - hash_token_secrets
    - head
    - puts
    - raise
    - redirect_to
    - render
    - require
    - require_relative
  Exclude:
    - db/migrate/*.rb
    - test/dummy/config/puma.rb

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Style/TrailingCommaInBlockArgs:
  Enabled: true
