language: ruby
cache: bundler

rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0

gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_6_1.gemfile

jobs:
  exclude:
    - rvm: 3.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 3.0
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 3.0
      gemfile: gemfiles/rails_5_2.gemfile
  include:
    - rvm: 2.7
      gemfile: gemfiles/rails_6_1.gemfile
      script: bundle exec rubocop
